# This configuration does not include a processing node
# Which makes for faster setup times
volumes:
  dbdata:
  appmedia:
services:
  db:
    build:
      context: ./db
    image: opendronemap/webodm_db
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=webodm_dev
    expose:
      - "5432"
    volumes:
      - type: bind
        source: ${WO_DB_DIR}
        target: /var/lib/postgresql/data
        bind:
          selinux: z
    restart: unless-stopped
    oom_score_adj: -100
  webapp:
    build:
      context: .
    image: webodm_webapp_local
    container_name: webapp
    entrypoint: /bin/bash -c "service cron start && chmod +x /webodm/*.sh && /bin/bash -c \"/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/start.sh\""
    volumes:
      - type: bind
        source: ${WO_MEDIA_DIR}
        target: /webodm/app/media
        bind:
          selinux: z
    ports:
      - "${WO_PORT}:8000"
    depends_on:
      - db
      - broker
      - worker
    environment:
      - WO_PORT
      - WO_HOST
      - WO_DEBUG
      - WO_BROKER
      - WO_DEV
      - WO_DEV_WATCH_PLUGINS
      - WO_SECRET_KEY
      - WEB_CONCURRENCY
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=webodm_dev
      - PGHOST=db
      - PGPORT=5432
    restart: unless-stopped
    oom_score_adj: 0
  broker:
    image: redis:7.0.10
    container_name: broker
    restart: unless-stopped
    oom_score_adj: -500
  worker:
    image: webodm_webapp_local
    container_name: worker
    entrypoint: /bin/bash -c "/webodm/wait-for-postgres.sh db /webodm/wait-for-it.sh -t 0 broker:6379 -- /webodm/wait-for-it.sh -t 0 webapp:8000 -- /webodm/worker.sh start"
    volumes:
      - type: bind
        source: ${WO_MEDIA_DIR}
        target: /webodm/app/media
        bind:
          selinux: z
    depends_on:
      - db
      - broker
    environment:
      - WO_BROKER
      - WO_DEBUG
      - WO_SECRET_KEY
      - WEB_CONCURRENCY
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - PGDATABASE=webodm_dev
      - PGHOST=db
      - PGPORT=5432
    restart: unless-stopped
    oom_score_adj: 250
  yamlnodeodm:
    image: opendronemap/nodeodm
    container_name: nodeodm
    ports:
      - "3001:3000"
    environment:
      - WO_HOST=webapp
